#define REDIS_GIT_SHA1 "ece62e3d"
#define REDIS_GIT_DIRTY "32"
#define REDIS_BUILD_ID "Chriss-1701688036"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
